apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: scores-deployment
spec:
  selector:
    matchLabels:
      app: scores
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: scores
    spec:
      containers:
      - name: scores
        image: ancina/scores:latest
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP

      livenessProbe:
        tcpSocket:
          port: 8083
        initialDelaySeconds: 15
        periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: scores
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: scores
