kumuluzee:
  name: scores-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  metrics:
    servlet:
      enabled: true
      mapping: /metrics

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23